{
 "title": "Database Exporter (PostgreSQL / MySQL)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  {
   "title": "Cкорость обращений к PostgreSQL (QPS)",
   "type": "gauge",
   "description": "скорость обращений к PostgreSQL-порту или любому другому процессу",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{device=\"eth0\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load (1 min average)",
   "type": "timeseries",
   "description": "Средняя системная нагрузка за 1 минуту",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "node_load1\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime системы",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Processes",
   "type": "stat",
   "description": "Количество активных процессов в системе",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_procs_running\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Filesystem Usage per Mountpoint",
   "type": "timeseries",
   "description": "Загруженность разных дисков или разделов\nИспользуй “Group by mountpoint”.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Scrapes Done (Prometheus)",
   "type": "barchart",
   "description": "сколько раз Prometheus собирал метрики",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds_count\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "процент использования RAM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер базы данных (в байтах → ГБ)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname!~\"$query0\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS (запросы в секунду)",
   "type": "timeseries",
   "description": "Динамика активности запросов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(pg_stat_activity_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Запись блоков",
   "type": "timeseries",
   "description": "Динамика операций записи",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Чтение блоков",
   "type": "timeseries",
   "description": "Динамика операций чтения",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"$query0\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер базы (ГБ)",
   "type": "gauge",
   "description": "Статус использования базы",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$query0\"} / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активные подключения",
   "type": "timeseries",
   "description": "Показывает количество текущих подключений к базе",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"$query0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}