{
 "title": "Node Exporter (Системные метрики)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of running processes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Swap usage (в %)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Inodes Usage (%)",
   "type": "stat",
   "description": "Показывает использование inode (количество файлов на диске)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_files_free{fstype!=\"tmpfs\"} / node_filesystem_files{fstype!=\"tmpfs\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "timeseries",
   "description": "Отображает, сколько работает система",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic (Mbit/sec)",
   "type": "timeseries",
   "description": "Показывает входящий и исходящий сетевой трафик",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[2m]) * 8 / 1000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[2m]) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Free Space (GB)",
   "type": "timeseries",
   "description": "чтение и запись",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total, Free, Used Memory (GB)",
   "type": "bargauge",
   "description": "Три панели — общая, свободная и используемая память",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Load (1, 5, 15 мин)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage per core (%)",
   "type": "gauge",
   "description": "Показывает загрузку каждого ядра (в процентах)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}