{
 "title": "Custom Exporter (внешние API)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "label_values(city)" } }
  ]
 },
 "panels": [
  {
   "title": "Отношение температуры к скорости ветра",
   "type": "timeseries",
   "description": "Псевдо-метрика: \"насколько тёплая погода при данном ветре\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"$query0\"} / weather_windspeed_kmh",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя температура и скорость ветра",
   "type": "barchart",
   "description": "Демонстрация группировки/агрегации",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(weather_temperature_celsius{city=\"$query0\"}) or (avg(weather_windspeed_kmh))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статус API (1 — работает, 0 — недоступно)",
   "type": "stat",
   "description": "Проверка доступности API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_api_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Динамика температуры (температурный тренд)",
   "type": "timeseries",
   "description": "Положительное — потепление, отрицательное — похолодание",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "deriv(weather_temperature_celsius[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Изменение скорости ветра (динамика)",
   "type": "timeseries",
   "description": "Показывает ускорение ветра (рост или спад)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "deriv(weather_windspeed_kmh{city=\"$query0\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя скорость ветра за 30 мин",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg_over_time(weather_windspeed_kmh[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущая скорость ветра",
   "type": "gauge",
   "description": "Просто текущее значение ветра",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_windspeed_kmh{city=\"$query0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Минимальная и максимальная температура за 1 час",
   "type": "bargauge",
   "description": "Диапазон колебаний температуры",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(weather_temperature_celsius{city=\"$query0\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущая температура в Астане",
   "type": "stat",
   "description": "Показывает текущую температуру ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"$query0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя температура",
   "type": "timeseries",
   "description": "Показывает, как менялась температура с течением времени.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "avg(weather_temperature_celsius{city=\"$query0\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}